//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarTrumpet.HardwareControls.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarTrumpet.HardwareControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add New From Selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddNewFromSelectedText {
            get {
                return ResourceManager.GetString("AddNewFromSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddNewText {
            get {
                return ResourceManager.GetString("AddNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *All Devices* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AllAudioDevicesSelectionText {
            get {
                return ResourceManager.GetString("AllAudioDevicesSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Mute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationMuteText {
            get {
                return ResourceManager.GetString("ApplicationMuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationSelectionText {
            get {
                return ResourceManager.GetString("ApplicationSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationVolumeText {
            get {
                return ResourceManager.GetString("ApplicationVolumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Mute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioDeviceMuteText {
            get {
                return ResourceManager.GetString("AudioDeviceMuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioDeviceText {
            get {
                return ResourceManager.GetString("AudioDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioDeviceVolumeText {
            get {
                return ResourceManager.GetString("AudioDeviceVolumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Button に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommandText {
            get {
                return ResourceManager.GetString("CommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ControlText {
            get {
                return ResourceManager.GetString("ControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle Default Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CycleDefaultDevices {
            get {
                return ResourceManager.GetString("CycleDefaultDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrease に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DecreaseText {
            get {
                return ResourceManager.GetString("DecreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   deej Control Wizard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeejControlWizardText {
            get {
                return ResourceManager.GetString("DeejControlWizardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteSelectedText {
            get {
                return ResourceManager.GetString("DeleteSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceText {
            get {
                return ResourceManager.GetString("DeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceTypeText {
            get {
                return ResourceManager.GetString("DeviceTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Time (Seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayTimeText {
            get {
                return ResourceManager.GetString("DisplayTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditSelectedText {
            get {
                return ResourceManager.GetString("EditSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Overlay に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnableOverlayText {
            get {
                return ResourceManager.GetString("EnableOverlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control system- and application volumes using a controller hardware (MIDI and deej devices supported). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareControlInformation {
            get {
                return ResourceManager.GetString("HardwareControlInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hardware Controls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareControlsTitle {
            get {
                return ResourceManager.GetString("HardwareControlsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release the selected button and click corresponding &apos;Set&apos; (while released). Then press the selected button and click corresponding &apos;Set&apos; (while pressed). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareControlWizardMinMaxButtonControlTypeInstructions {
            get {
                return ResourceManager.GetString("HardwareControlWizardMinMaxButtonControlTypeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the selected control to the minimum value and click corresponding &apos;Set&apos;. Then move the selected control to the maximum value and click corresponding &apos;Set&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareControlWizardMinMaxLinearPotentiometerControlTypeInstructions {
            get {
                return ResourceManager.GetString("HardwareControlWizardMinMaxLinearPotentiometerControlTypeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn the selected rotary control in decreasing direction and click corresponding &apos;Set&apos;. Then turn the selected rotary control in increasing direction and click corresponding &apos;Set&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareControlWizardMinMaxRotaryEncoderControlTypeInstructions {
            get {
                return ResourceManager.GetString("HardwareControlWizardMinMaxRotaryEncoderControlTypeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add / Edit Hardware Control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareSettingsText {
            get {
                return ResourceManager.GetString("HardwareSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move / press the hardware control element to be used. -&gt; Captured changes are listed in the table below. -&gt; Select the control to be assigned. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareWizardInstructions {
            get {
                return ResourceManager.GetString("HardwareWizardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incomplete device configuration! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncompleteDeviceConfigurationMessage {
            get {
                return ResourceManager.GetString("IncompleteDeviceConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncreaseText {
            get {
                return ResourceManager.GetString("IncreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indexed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IndexedText {
            get {
                return ResourceManager.GetString("IndexedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Linear Potentiometer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LinearPotentiometerText {
            get {
                return ResourceManager.GetString("LinearPotentiometerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaximumText {
            get {
                return ResourceManager.GetString("MaximumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDI Control Wizard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MidiControlWizardText {
            get {
                return ResourceManager.GetString("MidiControlWizardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDI Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MidiDeviceText {
            get {
                return ResourceManager.GetString("MidiDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MinimumText {
            get {
                return ResourceManager.GetString("MinimumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeText {
            get {
                return ResourceManager.GetString("ModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No control selected! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoControlSelectedMessage {
            get {
                return ResourceManager.GetString("NoControlSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show an overlay when changing volumes using hardware controls. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OSDInformation {
            get {
                return ResourceManager.GetString("OSDInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OverlayTitle {
            get {
                return ResourceManager.GetString("OverlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PositionText {
            get {
                return ResourceManager.GetString("PositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreviewValueText {
            get {
                return ResourceManager.GetString("PreviewValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pushed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PushedText {
            get {
                return ResourceManager.GetString("PushedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Released に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReleasedText {
            get {
                return ResourceManager.GetString("ReleasedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotary Encoder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RotaryEncoderText {
            get {
                return ResourceManager.GetString("RotaryEncoderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScalingText {
            get {
                return ResourceManager.GetString("ScalingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectionText {
            get {
                return ResourceManager.GetString("SelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set As Default Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetAsDefaultDevice {
            get {
                return ResourceManager.GetString("SetAsDefaultDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetText {
            get {
                return ResourceManager.GetString("SetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown device selected! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnknownDeviceSelectedMessageText {
            get {
                return ResourceManager.GetString("UnknownDeviceSelectedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown device type selected! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnknownDeviceTypeSelectedMessageText {
            get {
                return ResourceManager.GetString("UnknownDeviceTypeSelectedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X-Offset (Pixels) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XOffsetText {
            get {
                return ResourceManager.GetString("XOffsetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y-Offset (Pixels) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YOffsetText {
            get {
                return ResourceManager.GetString("YOffsetText", resourceCulture);
            }
        }
    }
}
